python basic_3.py ./datapoints/in1.txt ./datapoints/out1.txt
python basic_3.py ./datapoints/in2.txt ./datapoints/out2.txt
python basic_3.py ./datapoints/in3.txt ./datapoints/out3.txt
python basic_3.py ./datapoints/in4.txt ./datapoints/out4.txt
python basic_3.py ./datapoints/in5.txt ./datapoints/out5.txt
python basic_3.py ./datapoints/in6.txt ./datapoints/out6.txt
python basic_3.py ./datapoints/in7.txt ./datapoints/out7.txt
python basic_3.py ./datapoints/in8.txt ./datapoints/out8.txt
python basic_3.py ./datapoints/in9.txt ./datapoints/out9.txt
python basic_3.py ./datapoints/in10.txt ./datapoints/out10.txt
python basic_3.py ./datapoints/in11.txt ./datapoints/out11.txt
python basic_3.py ./datapoints/in12.txt ./datapoints/out12.txt
python basic_3.py ./datapoints/in13.txt ./datapoints/out13.txt
python basic_3.py ./datapoints/in14.txt ./datapoints/out14.txt
python basic_3.py ./datapoints/in15.txt ./datapoints/out15.txt