python efficient_3.py ./datapoints/in1.txt ./datapoints/oute1.txt
python efficient_3.py ./datapoints/in2.txt ./datapoints/oute2.txt
python efficient_3.py ./datapoints/in3.txt ./datapoints/oute3.txt
python efficient_3.py ./datapoints/in4.txt ./datapoints/oute4.txt
python efficient_3.py ./datapoints/in5.txt ./datapoints/oute5.txt
python efficient_3.py ./datapoints/in6.txt ./datapoints/oute6.txt
python efficient_3.py ./datapoints/in7.txt ./datapoints/oute7.txt
python efficient_3.py ./datapoints/in8.txt ./datapoints/oute8.txt
python efficient_3.py ./datapoints/in9.txt ./datapoints/oute9.txt
python efficient_3.py ./datapoints/in10.txt ./datapoints/oute10.txt
python efficient_3.py ./datapoints/in11.txt ./datapoints/oute11.txt
python efficient_3.py ./datapoints/in12.txt ./datapoints/oute12.txt
python efficient_3.py ./datapoints/in13.txt ./datapoints/oute13.txt
python efficient_3.py ./datapoints/in14.txt ./datapoints/oute14.txt
python efficient_3.py ./datapoints/in15.txt ./datapoints/oute15.txt